async function getCurrentTab() {
    let queryOptions = { active: true, lastFocusedWindow: true };
    // `tab` will either be a `tabs.Tab` instance or `undefined`.
    let [tab] = await chrome.tabs.query(queryOptions);
    return tab;
  }

let thetab;

function changeBackgroundImage(url) {
  const mainElement = document.querySelector('.main');
  mainElement.style.backgroundImage = `url('${url}')`;
}

const regex = new RegExp('^(?!https?:\/\/)([a-zA-Z0-9+.-]+:\/\/).*') //checks if a tab is a valid tab (not chrome://newtab etc etc) Generated by chatgpt

getCurrentTab().then(tab => {
    thetab = tab;
    console.log(thetab.url);
    if(regex.test(thetab.url)) {
      const loadingtext = document.querySelector('.loading')
      loadingtext.textContent = "This tab isn't supported!"
      const loadingimage = document.querySelector('.loadingmiku')
      loadingimage.src = ""
    }
});